// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
type CSSModuleClasses = { readonly [key: string]: string }

declare module '*.less' {
  const classes: CSSModuleClasses
  export default classes
}

declare interface CordovaPlugins {
  StatusBarHeight?: {
    getValue: ( successFn: (value: number) => void, FailFn: (value: string) => void ) => void;
  }
}
